language: node_js
node_js:
  - 'node'
  - '8'
  - '6'
# FIXME: because travis still uses Mongo 2.4 and we want Mongo 3 we install it manually
services:
 - mongodb
addons:
  code_climate:
    repo_token: 'd6589258f9a1e18f8dc6e4c1700d960c00298e1a8618bb9cde99ceaaded49398'
notifications:
  email: false
# before_install:
#  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
#  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
#  - "sudo apt-get update"
#  - "sudo apt-get install mongodb-org-server"
before_script:
#  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - sleep 15

after_success: npm run coverage
